data = read_csv_file('results.csv')
no_duplicates_data = remove_duplicates(data)
no_empty_lines_data = ignore_empty_lines(no_duplicates_data)
capitalized_data = capitalize_names(no_empty_lines_data)
validated_data = validate_answer_3(capitalized_data)
write_clean_data(validated_data)
output(validated_data)