def test_read_csv_file():
    expected = [
        {
            "user_id": "1",
            "first_name": "Charissa",
            "last_name": "Clark",
            "answer_1": "yes",
            "answer_2": "c",
            "answer_3": "7",
        },
        {
            "user_id": "2",
            "first_name": "richard",
            "last_name": "McKinney",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "7",
        },
        {
            "user_id": "",
            "first_name": "",
            "last_name": "",
            "answer_1": "",
            "answer_2": "",
            "answer_3": "",
        },
        {
            "user_id": "3",
            "first_name": "patience",
            "last_name": "reeves",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "9",
        },
        {
            "user_id": "4",
            "first_name": "Harding",
            "last_name": "Estrada",
            "answer_1": "no",
            "answer_2": "b",
            "answer_3": "14",
        },
        {
            "user_id": "5",
            "first_name": "India",
            "last_name": "Gentry",
            "answer_1": "yes",
            "answer_2": "c",
            "answer_3": "7",
        },
        {
            "user_id": "6",
            "first_name": "Abra",
            "last_name": "Sheppard",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "6",
        },
        {
            "user_id": "6",
            "first_name": "Abra",
            "last_name": "Sheppard",
            "answer_1": "no",
            "answer_2": "a",
            "answer_3": "8",
        },
        {
            "user_id": "7",
            "first_name": "Bryar",
            "last_name": "cooley",
            "answer_1": "yes",
            "answer_2": "a",
            "answer_3": "11",
        },
        {
            "user_id": "8",
            "first_name": "Diana",
            "last_name": "Cameron",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "9",
        },
        {
            "user_id": "9",
            "first_name": "Alexander",
            "last_name": "Herring",
            "answer_1": "no",
            "answer_2": "b",
            "answer_3": "4",
        },
        {
            "user_id": "10",
            "first_name": "Graiden",
            "last_name": "Cannon",
            "answer_1": "no",
            "answer_2": "b",
            "answer_3": "13",
        },
        {
            "user_id": "11",
            "first_name": "Uma",
            "last_name": "Glass",
            "answer_1": "yes",
            "answer_2": "a",
            "answer_3": "2",
        },
        {
            "user_id": "12",
            "first_name": "Brittany",
            "last_name": "Weeks",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "8",
        },
        {
            "user_id": "13",
            "first_name": "Roth",
            "last_name": "Stout",
            "answer_1": "yes",
            "answer_2": "c",
            "answer_3": "10",
        },
        {
            "user_id": "14",
            "first_name": "Amos",
            "last_name": "Daniel",
            "answer_1": "yes",
            "answer_2": "a",
            "answer_3": "5",
        },
        {
            "user_id": "",
            "first_name": "",
            "last_name": "",
            "answer_1": "",
            "answer_2": "",
            "answer_3": "",
        },
        {
            "user_id": "15",
            "first_name": "Caesar",
            "last_name": "Rivers",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "7",
        },
        {
            "user_id": "16",
            "first_name": "Eugenia",
            "last_name": "Nichols",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "6",
        },
        {
            "user_id": "17",
            "first_name": "dieter",
            "last_name": "alvarado",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "6",
        },
        {
            "user_id": "17",
            "first_name": "Dieter",
            "last_name": "Alvarado",
            "answer_1": "no",
            "answer_2": "c",
            "answer_3": "7",
        },
        {
            "user_id": "17",
            "first_name": "Dieter",
            "last_name": "Alvarado",
            "answer_1": "yes",
            "answer_2": "a",
            "answer_3": "9",
        },
        {
            "user_id": "18",
            "first_name": "Roary",
            "last_name": "Frank",
            "answer_1": "yes",
            "answer_2": "c",
            "answer_3": "7",
        },
        {
            "user_id": "19",
            "first_name": "Ulric",
            "last_name": "Hensley",
            "answer_1": "no",
            "answer_2": "b",
            "answer_3": "9",
        },
        {
            "user_id": "20",
            "first_name": "Felicia",
            "last_name": "Wilkins",
            "answer_1": "yes",
            "answer_2": "b",
            "answer_3": "8",
        },
    ]
    assert read_csv_file("results.csv") == expected
